using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace PixieLib.Generators;

// Turns each *.template.cs of PixieLib into the three precisions of the primitive: double with no
// suffix, float with f and int with i (docs/notas.md, 4.1). C# has no templates and the generic math
// of INumber<T> does not exist in net481, so the code is written once and copied by this generator.
//
// In the template, __S__ is the suffix and __T__ the type. Each copy starts with #define lines, so the
// template keeps the differences in plain #if blocks: PX_DOUBLE, PX_FLOAT and PX_INT name the
// precision, and PX_FLOATING is set for both double and float.
[Generator]
public sealed class PrecisionGenerator : IIncrementalGenerator
{
    private const string TemplateSuffix = ".template.cs";

    private static readonly (string Suffix, string Type, string Defines)[] Precisions =
    {
        ("", "double", "#define PX_DOUBLE\n#define PX_FLOATING\n"),
        ("f", "float", "#define PX_FLOAT\n#define PX_FLOATING\n"),
        ("i", "int", "#define PX_INT\n"),
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var templates = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(TemplateSuffix, System.StringComparison.Ordinal));

        context.RegisterSourceOutput(templates, static (output, file) =>
        {
            string name = Path.GetFileName(file.Path);
            name = name.Substring(0, name.Length - TemplateSuffix.Length);
            string? text = file.GetText(output.CancellationToken)?.ToString();
            if (text is null)
                return;

            foreach (var (suffix, type, defines) in Precisions)
            {
                string code = "// <auto-generated/> from " + name + TemplateSuffix + "\n"
                    + defines
                    + "#nullable enable\n"
                    + text.Replace("__S__", suffix).Replace("__T__", type);
                output.AddSource(name + suffix + ".g.cs", SourceText.From(code, Encoding.UTF8));
            }
        });
    }
}
